services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fullstack_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack_app
    depends_on:
      - postgres
    env_file:
      - .env.production
    ports:
      - "5000:5000"

nginx:
  image: nginx:alpine
  container_name: nginx_proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs:/etc/nginx/certs:ro
  depends_on:
    - fullstack_app

volumes:
  postgres_data:
